services:
  uploadje-api:
    image: uploadje-api:latest
    ports:
      - "${PORT}:3000"
    environment:
      - PORT
      - DB_URL
      - JWT_SECRET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  db:
      image: postgres:latest
      environment:
        - POSTGRES_PASSWORD=mysecretpassword
        - POSTGRES_DATABASE=uploadjeapi
      ports:
        - "5432:5432"